### ISSUE TITLE
"NoSuchKey: The specified key does not exist" on deploy

### ISSUE THREAD

**Issue by raytio** [ownstats/ownstats#2]
When I attempt to deploy ownstats I get an error at the end of the deployment:
```
Serverless: Stack update finished...
Serverless: Invoke aws:info
Serverless: [AWS cloudformation 200 0.87s 0 retries] describeStacks({ StackName: 'raytio-web-stats-dev' })
Serverless: [AWS cloudformation 200 0.859s 0 retries] listStackResources({ StackName: 'raytio-web-stats-dev' })
Service Information
service: raytio-web-stats
stage: dev
region: us-east-1
stack: raytio-web-stats-dev
resources: 29
api keys:
  None
endpoints:
  CloudFront - d3dfiqfbrgk5v0.cloudfront.net
functions:
  transformPageViews: raytio-web-stats-dev-transformPageViews
  createPartition: raytio-web-stats-dev-createPartition
  moveAccessLogs: raytio-web-stats-dev-moveAccessLogs
layers:
  None
Serverless: WARNING: Inappropriate call of provider.request()
S3 Sync: Syncing directories and S3 prefixes...
Serverless: [AWS cloudformation 200 0.815s 0 retries] describeStacks({ StackName: 'raytio-web-stats-dev' })
Serverless: Minified hello.js
Serverless: Stack Output processed with handler: modules/finalize.handler
Serverless: [AWS s3 200 0.968s 0 retries] listObjects({ Bucket: 'raytio-web-stats', Marker: null, MaxKeys: null, Prefix: '' })
Serverless: Compressed hello.js
.Serverless: Written hello.js template: /home/cameron_beattie/Documents/VSCode_projects/web-stats/src/hello.js
Serverless: Tracking pixel URL: https://d3dfiqfbrgk5v0.cloudfront.net/hello.gif
Serverless: Tracking script URL: https://d3dfiqfbrgk5v0.cloudfront.net/hello.js
Serverless: You can now add '<script src="https://d3dfiqfbrgk5v0.cloudfront.net/hello.js"></script>' to your website's sources to enable the gathering of statistics
Serverless: [AWS s3 200 0.996s 0 retries] listObjects({
  Bucket: 'raytio-web-stats-logs',
  Marker: null,
  MaxKeys: null,
  Prefix: 'edge-locations/'
})
.Serverless: [AWS s3 200 0.991s 0 retries] putObject({
  Bucket: 'raytio-web-stats',
  ACL: 'private',
  ContentType: 'image/gif',
  Key: 'hello.gif',
  ContentLength: 42,
  Body: MultipartETag {
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: null,
      pipesCount: 0,
      flowing: false,
      ended: true,
      endEmitted: true,
      reading: false,
      sync: false,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      paused: false,
      emitClose: true,
      autoDestroy: false,
      destroyed: false,
      defaultEncoding: 'utf8',
      awaitDrain: 0,
      readingMore: false,
      decoder: null,
      encoding: null
    },
    readable: false,
    [domain]: null,
    _events: [Object: null prototype] {
      prefinish: [Function: prefinish] {
        [length]: 0,
        [name]: 'prefinish',
        [prototype]: prefinish { [constructor]: [Circular] }
      },
      end: [Function] {
        [length]: 0,
        [name]: '',
        [arguments]: null,
        [caller]: null,
        [prototype]: { [constructor]: [Circular] }
      },
      progress: [Function] {
        [length]: 0,
        [name]: '',
        [arguments]: null,
        [caller]: null,
        [prototype]: { [constructor]: [Circular] }
      }
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: true,
      ended: true,
      finished: true,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite] { [length]: 1, [name]: 'bound onwrite' },
      writecb: null,
      writelen: 0,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: true,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: {
        next: null,
        entry: null,
        finish: [Function: bound onCorkedFinish] {
          [length]: 1,
          [name]: 'bound onCorkedFinish'
        }
      }
    },
    writable: false,
    allowHalfOpen: true,
    _transformState: {
      afterTransform: [Function: bound afterTransform] {
        [length]: 2,
        [name]: 'bound afterTransform'
      },
      needTransform: false,
      transforming: false,
      writecb: null,
      writechunk: null,
      writeencoding: 'buffer'
    },
    sums: [
      {
        size: 5368709120,
        hash: Hash {
          _options: undefined,
          writable: true,
          readable: true,
          [Symbol(kHandle)]: {},
          [Symbol(kState)]: { [Symbol(kFinalized)]: true }
        },
        amtWritten: 42,
        digests: [
          <Buffer d8 97 46 88 8d a2 d9 51 0b 64 a9 f0 31 ea ec d5>,
          [length]: 1
        ],
        eTag: '240d58ec239fd114f5301c78b37950d0-1'
      },
      [length]: 1
    ],
    bytes: 42,
    digest: <Buffer d8 97 46 88 8d a2 d9 51 0b 64 a9 f0 31 ea ec d5>,
    done: true
  }
})
Serverless: [AWS s3 200 1.029s 0 retries] putObject({
  Bucket: 'raytio-web-stats-logs',
  ACL: 'private',
  Key: 'edge-locations/edge-locations.csv',
  ContentType: 'text/csv',
  ContentLength: 5367,
  Body: MultipartETag {
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: null,
      pipesCount: 0,
      flowing: false,
      ended: true,
      endEmitted: true,
      reading: false,
      sync: false,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      paused: false,
      emitClose: true,
      autoDestroy: false,
      destroyed: false,
      defaultEncoding: 'utf8',
      awaitDrain: 0,
      readingMore: false,
      decoder: null,
      encoding: null
    },
    readable: false,
    [domain]: null,
    _events: [Object: null prototype] {
      prefinish: [Function: prefinish] {
        [length]: 0,
        [name]: 'prefinish',
        [prototype]: prefinish { [constructor]: [Circular] }
      },
      end: [Function] {
        [length]: 0,
        [name]: '',
        [arguments]: null,
        [caller]: null,
        [prototype]: { [constructor]: [Circular] }
      },
      progress: [Function] {
        [length]: 0,
        [name]: '',
        [arguments]: null,
        [caller]: null,
        [prototype]: { [constructor]: [Circular] }
      }
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: true,
      ended: true,
      finished: true,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite] { [length]: 1, [name]: 'bound onwrite' },
      writecb: null,
      writelen: 0,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: true,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: {
        next: null,
        entry: null,
        finish: [Function: bound onCorkedFinish] {
          [length]: 1,
          [name]: 'bound onCorkedFinish'
        }
      }
    },
    writable: false,
    allowHalfOpen: true,
    _transformState: {
      afterTransform: [Function: bound afterTransform] {
        [length]: 2,
        [name]: 'bound afterTransform'
      },
      needTransform: false,
      transforming: false,
      writecb: null,
      writechunk: null,
      writeencoding: 'buffer'
    },
    sums: [
      {
        size: 5368709120,
        hash: Hash {
          _options: undefined,
          writable: true,
          readable: true,
          [Symbol(kHandle)]: {},
          [Symbol(kState)]: { [Symbol(kFinalized)]: true }
        },
        amtWritten: 5367,
        digests: [
          <Buffer b5 c5 0c 04 82 13 49 bc 34 ba fe d4 d1 16 1f d0>,
          [length]: 1
        ],
        eTag: '207898453c4be12b4cd66c7b95406064-1'
      },
      [length]: 1
    ],
    bytes: 5367,
    digest: <Buffer b5 c5 0c 04 82 13 49 bc 34 ba fe d4 d1 16 1f d0>,
    done: true
  }
})
.
S3 Sync: Synced.
S3 Sync: Syncing metadata...
Serverless: [AWS s3 404 0.805s 0 retries] copyObject({
  ContentType: 'application/javascript',
  ContentEncoding: 'gzip',
  CopySource: 'raytio-web-stats/hello.js',
  Key: 'hello.js',
  Bucket: 'raytio-web-stats',
  ACL: 'private',
  MetadataDirective: 'REPLACE'
})
 
  No Such Key --------------------------------------------
 
  NoSuchKey: The specified key does not exist.
      at Request.extractError (/snapshot/serverless/node_modules/aws-sdk/lib/services/s3.js:816:35)
      at Request.callListeners (/snapshot/serverless/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
      at Request.emit (/snapshot/serverless/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (/snapshot/serverless/node_modules/aws-sdk/lib/request.js:683:14)
      at Request.transition (/snapshot/serverless/node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (/snapshot/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
      at /snapshot/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (/snapshot/serverless/node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (/snapshot/serverless/node_modules/aws-sdk/lib/request.js:685:12)
      at Request.callListeners (/snapshot/serverless/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
      at Request.emit (/snapshot/serverless/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (/snapshot/serverless/node_modules/aws-sdk/lib/request.js:683:14)
      at Request.transition (/snapshot/serverless/node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (/snapshot/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
      at /snapshot/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (/snapshot/serverless/node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (/snapshot/serverless/node_modules/aws-sdk/lib/request.js:685:12)
      at Request.callListeners (/snapshot/serverless/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
      at callNextListener (/snapshot/serverless/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
      at IncomingMessage.onEnd (/snapshot/serverless/node_modules/aws-sdk/lib/event_listeners.js:307:13)
      at IncomingMessage.emit (events.js:215:7)
      at IncomingMessage.EventEmitter.emit (domain.js:475:20)
      at endReadableNT (_stream_readable.js:1184:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.13.1
     Framework Version:         1.61.3 (standalone)
     Plugin Version:            3.2.7
     SDK Version:               2.3.0
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0
```

`raytio-web-stats/hello.js` does not exist and I can't figure out what is supposed to create that. Incidentally `raytio-web-stats/hello.gif` does exist.

Any sugggestions appreciated.

**Comment by tobilg** [comment]
Thanks for reporting. That's a bit strange, as both files should reside in the `src/` folder and not the root folder as you were writing.

The `hello.js` file is created on the fly by https://github.com/ownstats/ownstats/blob/master/modules/finalize.js after the provisioning of the stacak is finished. Can you please look in the `src/` folder if it was generated? If yes, you can run `sls s3sync` manually to upload it to S3.

**Comment by tobilg** [comment]
The log lines 

```bash
Serverless: Compressed hello.js
.Serverless: Written hello.js template: /home/cameron_beattie/Documents/VSCode_projects/web-stats/src/hello.js
```

seem to indicate that the `hello.js` file actually was created, but in the `web-stats/src` folder, and not `raytio-web-stats/`. Have you eventually renamed the folder?

**Comment by raytio** [comment]
Thanks. Yes both files exist in the src directory. However `hello,js` appears to be a binary file rather than text/javascript.

**Comment by tobilg** [comment]
Yes, it's a compressed/gzipped JS file. That's fine. I just wonder where the error message originates from then, because there seems to be an obvious mismatch between the paths...

**Comment by raytio** [comment]
Ah I understand.

Serverless service (and s3 folder) name : `raytio-web-stats`
Local directory name `web-stats`

Is it expecting that service name == directory name?

**Comment by tobilg** [comment]
No, it doesn't expect that. Just tried it on my machine and it works perfectly fine. Can you do a `sls s3sync` from the root folder of the project and report back what happens?

**Comment by raytio** [comment]
That works fine. Both files are now present in the s3 bucket so not sure what the problem was. Many thanks for your help.

**Comment by tobilg** [comment]
Ok great, no worries.
