### ISSUE TITLE
"Unresolved resource dependencies [OwnstatsDatabase]" on deploy

### ISSUE THREAD

**Issue by raytio** [ownstats/ownstats#3]
When attempting to deploy I get:
```
Serverless: Validating template...
Serverless: [AWS cloudformation 400 1.159s 0 retries] validateTemplate({
  TemplateURL: 'https://s3.amazonaws.com/ownstats-dev-serverlessdeploymentbucket-zcsdi80rubbe/serverless/ownstats/dev/1591383867673-2020-06-05T19:04:27.673Z/compiled-cloudformation-template.json'
})
 
  Error --------------------------------------------------
 
  Error: The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [OwnstatsDatabase] in the Resources block of the template
      at /snapshot/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:20:13
  From previous event:
      at AwsDeploy.validateTemplate (/snapshot/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:16:85)
  From previous event:
      at AwsDeploy.<anonymous> (/snapshot/serverless/lib/plugins/aws/deploy/index.js:119:39)
  From previous event:
      at Object.aws:deploy:deploy:validateTemplate [as hook] (/snapshot/serverless/lib/plugins/aws/deploy/index.js:115:30)
      at /snapshot/serverless/lib/classes/PluginManager.js:490:55
  From previous event:
      at PluginManager.invoke (/snapshot/serverless/lib/classes/PluginManager.js:490:22)
      at PluginManager.spawn (/snapshot/serverless/lib/classes/PluginManager.js:510:17)
      at AwsDeploy.<anonymous> (/snapshot/serverless/lib/plugins/aws/deploy/index.js:93:48)
  From previous event:
      at Object.deploy:deploy [as hook] (/snapshot/serverless/lib/plugins/aws/deploy/index.js:89:30)
      at /snapshot/serverless/lib/classes/PluginManager.js:490:55
  From previous event:
      at PluginManager.invoke (/snapshot/serverless/lib/classes/PluginManager.js:490:22)
      at /snapshot/serverless/lib/classes/PluginManager.js:525:24
  From previous event:
      at PluginManager.run (/snapshot/serverless/lib/classes/PluginManager.js:525:8)
      at /snapshot/serverless/lib/Serverless.js:133:33
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:130:23)
  From previous event:
      at Serverless.run (/snapshot/serverless/lib/Serverless.js:120:74)
      at /snapshot/serverless/bin/serverless.js:75:30
      at /snapshot/serverless/node_modules/graceful-fs/graceful-fs.js:144:16
      at /snapshot/serverless/node_modules/graceful-fs/graceful-fs.js:65:14
      at FSReqCallback.oncomplete (fs.js:146:23)
  From previous event:
      at /snapshot/serverless/bin/serverless.js:75:8
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:130:23)
  From previous event:
      at Object.<anonymous> (/snapshot/serverless/bin/serverless.js:64:4)
      at Module._compile (pkg/prelude/bootstrap.js:1261:22)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
      at Module.load (internal/modules/cjs/loader.js:813:32)
      at Function.Module._load (internal/modules/cjs/loader.js:725:14)
      at Function.Module.runMain (pkg/prelude/bootstrap.js:1316:12)
      at internal/main/run_main_module.js:17:11
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.13.1
     Framework Version:         1.61.3 (standalone)
     Plugin Version:            3.2.7
     SDK Version:               2.3.0
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0
 ```

**Comment by tobilg** [comment]
Sorry for the inconvenience, I fixed this in ea33256fc423cf3cee571200600c2a2e3be007c7. Closing.
